function [fitresult, gof,output] = createFit1(l,n,start,stop)
%CREATEFIT1(L,N)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : l
%      Y Output: n
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jun-2018 17:33:14


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( l, n );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
% [fitresult, gof] = fit( xData(start:stop), yData(start:stop), ft );
[fitresult,gof,output] = fit( xData(start:stop), yData(start:stop), ft );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% hold
% plot( fitresult, xData(start:stop), yData(start:stop),'g');
% legend( h, 'n vs. l', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
% xlabel l
% ylabel n
% grid on
% hold


